export interface SkillCategory {
  id: string;
  name: string;
  skills: string[];
}

export const skillCategories: SkillCategory[] = [
  {
    id: "business-finance",
    name: "Business & Finance Skills",
    skills: [
      "Accounting/Bookkeeping",
      "Financial Planning",
      "Budget Management",
      "Tax Preparation",
      "Payroll Processing",
      "QuickBooks/Accounting Software",
      "Financial Analysis",
      "Auditing",
      "Investment Knowledge",
      "Business Strategy",
      "Project Management",
      "Operations Management",
      "Supply Chain Management",
      "Inventory Management",
      "Contract Negotiation",
      "Business Development",
      "Sales",
      "Cold Calling",
      "Client Relationship Management",
      "Fundraising",
      "Grant Writing",
      "Nonprofit Management"
    ]
  },
  {
    id: "technology-it",
    name: "Technology & IT Skills",
    skills: [
      "Web Development (HTML/CSS/JavaScript)",
      "Front-End Development",
      "Back-End Development",
      "Full-Stack Development",
      "Mobile App Development (iOS)",
      "Mobile App Development (Android)",
      "Python Programming",
      "Java Programming",
      "C++/C# Programming",
      "Database Management (SQL)",
      "Cloud Computing (AWS/Azure/Google Cloud)",
      "Cybersecurity",
      "Network Administration",
      "IT Support/Troubleshooting",
      "Software Testing/QA",
      "DevOps",
      "WordPress Development",
      "Shopify Development",
      "API Integration",
      "Game Development",
      "Blockchain/Cryptocurrency",
      "AI/Machine Learning",
      "Data Science",
      "Data Analytics",
      "Excel/Spreadsheet Expert",
      "Automation/Scripting"
    ]
  },
  {
    id: "creative-design",
    name: "Creative & Design Skills",
    skills: [
      "Graphic Design",
      "Logo Design",
      "Brand Identity Design",
      "UI/UX Design",
      "Web Design",
      "Print Design",
      "Illustration",
      "Digital Illustration",
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Adobe InDesign",
      "Figma",
      "Canva",
      "Video Editing",
      "Motion Graphics",
      "Animation (2D)",
      "Animation (3D)",
      "Photography",
      "Photo Editing/Retouching",
      "Product Photography",
      "Event Photography",
      "Videography",
      "Interior Design",
      "Fashion Design",
      "Jewelry Design",
      "CAD Design",
      "3D Modeling",
      "Packaging Design"
    ]
  },
  {
    id: "writing-content",
    name: "Writing & Content Skills",
    skills: [
      "Copywriting",
      "Content Writing",
      "Blog Writing",
      "Technical Writing",
      "Creative Writing",
      "Ghostwriting",
      "Grant Writing",
      "Resume Writing",
      "Cover Letter Writing",
      "Business Writing",
      "Email Marketing Copy",
      "SEO Writing",
      "Scriptwriting",
      "Speechwriting",
      "Social Media Writing",
      "Product Descriptions",
      "Press Releases",
      "White Papers",
      "Case Studies",
      "Editing/Proofreading",
      "Translation (specify languages)",
      "Transcription",
      "Subtitling/Captioning"
    ]
  },
  {
    id: "marketing-advertising",
    name: "Marketing & Advertising Skills",
    skills: [
      "Digital Marketing",
      "Social Media Marketing",
      "Social Media Management",
      "Content Marketing",
      "Email Marketing",
      "SEO (Search Engine Optimization)",
      "SEM/PPC (Google Ads)",
      "Facebook/Instagram Ads",
      "Influencer Marketing",
      "Affiliate Marketing",
      "Brand Strategy",
      "Market Research",
      "Competitor Analysis",
      "Marketing Analytics",
      "Conversion Rate Optimization",
      "Marketing Automation",
      "Public Relations",
      "Event Marketing",
      "Community Management",
      "Lead Generation",
      "Growth Hacking"
    ]
  },
  {
    id: "teaching-training",
    name: "Teaching & Training Skills",
    skills: [
      "Teaching/Instruction",
      "Curriculum Development",
      "Lesson Planning",
      "Tutoring",
      "Test Prep (SAT/ACT/GRE/GMAT)",
      "ESL/English Teaching",
      "Language Teaching (specify language)",
      "Math Tutoring",
      "Science Tutoring",
      "Music Instruction",
      "Art Instruction",
      "Fitness Training/Coaching",
      "Yoga Instruction",
      "Dance Instruction",
      "Corporate Training",
      "Instructional Design",
      "E-Learning Development",
      "Workshop Facilitation",
      "Public Speaking",
      "Presentation Skills",
      "Training Program Development"
    ]
  },
  {
    id: "healthcare-wellness",
    name: "Healthcare & Wellness Skills",
    skills: [
      "Nursing",
      "Medical Coding",
      "Medical Billing",
      "Healthcare Administration",
      "Physical Therapy",
      "Occupational Therapy",
      "Mental Health Counseling",
      "Life Coaching",
      "Health Coaching",
      "Nutrition Coaching",
      "Diet Planning",
      "Personal Training",
      "Massage Therapy",
      "Acupuncture",
      "Chiropractic Care",
      "Home Healthcare",
      "Elder Care",
      "Child Care",
      "Meditation Instruction",
      "Stress Management",
      "Holistic Health",
      "Pharmacy Technician"
    ]
  },
  {
    id: "hr-recruiting",
    name: "Human Resources & Recruiting Skills",
    skills: [
      "Recruiting/Talent Acquisition",
      "HR Management",
      "Employee Relations",
      "Benefits Administration",
      "Compensation Analysis",
      "Performance Management",
      "Training & Development",
      "Onboarding",
      "HR Compliance",
      "Conflict Resolution",
      "Career Coaching",
      "Resume Review",
      "Interview Coaching",
      "LinkedIn Profile Optimization",
      "Organizational Development"
    ]
  },
  {
    id: "trades-technical",
    name: "Trades & Technical Skills",
    skills: [
      "Carpentry",
      "Plumbing",
      "Electrical Work",
      "HVAC",
      "Auto Repair/Mechanics",
      "Welding",
      "Painting (Residential/Commercial)",
      "Landscaping",
      "Gardening",
      "Home Repair/Handyman",
      "Appliance Repair",
      "Roofing",
      "Flooring Installation",
      "Tile Work",
      "Drywall",
      "Furniture Assembly",
      "Pool Maintenance",
      "Pest Control"
    ]
  },
  {
    id: "entertainment-media",
    name: "Entertainment & Media Skills",
    skills: [
      "Acting",
      "Voice Acting/Voice Over",
      "Audio Editing",
      "Podcast Production",
      "Music Production",
      "Songwriting",
      "DJ Services",
      "Event Planning",
      "Wedding Planning",
      "MC/Host Services",
      "Comedy Writing",
      "Stand-Up Comedy",
      "Magic/Entertainment",
      "Makeup Artistry",
      "Hair Styling",
      "Wardrobe Styling",
      "Set Design",
      "Stage Management"
    ]
  },
  {
    id: "lifestyle-personal",
    name: "Lifestyle & Personal Services Skills",
    skills: [
      "Personal Assistance/Virtual Assistant",
      "Organizing/Decluttering",
      "Home Staging",
      "Pet Sitting",
      "Dog Walking",
      "Pet Grooming",
      "House Sitting",
      "Cleaning Services",
      "Meal Prep/Personal Chef",
      "Baking",
      "Catering",
      "Bartending",
      "Event Staffing",
      "Errand Running",
      "Moving/Packing Services",
      "Laundry Services",
      "Concierge Services"
    ]
  },
  {
    id: "legal-compliance",
    name: "Legal & Compliance Skills",
    skills: [
      "Paralegal Work",
      "Legal Research",
      "Contract Review",
      "Compliance Management",
      "Notary Services",
      "Immigration Assistance",
      "Patent Research",
      "Legal Writing",
      "Mediation",
      "Policy Development"
    ]
  },
  {
    id: "soft-skills",
    name: "Soft Skills & General Abilities",
    skills: [
      "Customer Service",
      "Problem Solving",
      "Critical Thinking",
      "Leadership",
      "Team Building",
      "Time Management",
      "Organization",
      "Communication (Written)",
      "Communication (Verbal)",
      "Active Listening",
      "Empathy/Emotional Intelligence",
      "Conflict Resolution",
      "Adaptability",
      "Creativity",
      "Attention to Detail",
      "Multitasking",
      "Research Skills",
      "Data Entry",
      "Administrative Support",
      "Calendar Management",
      "Travel Planning",
      "Event Coordination"
    ]
  }
];

export const commonLanguages = [
  "Spanish",
  "French",
  "German",
  "Mandarin Chinese",
  "Japanese",
  "Korean",
  "Arabic",
  "Portuguese",
  "Russian",
  "Italian",
  "Hindi",
  "Vietnamese",
  "Tagalog",
  "Polish",
  "Dutch",
  "Swedish",
  "Norwegian",
  "Danish",
  "Greek",
  "Hebrew",
  "Turkish",
  "Thai"
];
