import jsPDF from 'jspdf';

interface GrantContactInfo {
  name: string;
  title: string;
  email: string;
  phone: string;
}

export function generateGrantProposalPDF(
  proposal: string,
  loi: string,
  organizationName: string,
  projectTitle: string,
  contactInfo: GrantContactInfo
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Helper function to add text with automatic page breaks
  const addText = (text: string, fontSize: number = 11, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    
    const lines = doc.splitTextToSize(text, maxWidth);
    
    lines.forEach((line: string) => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
        // Add footer to previous page
        addFooter();
      }
      doc.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    });
  };

  // Helper function to add footer
  const addFooter = () => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(128, 128, 128);
      doc.text(
        `Generated by PivotHub | Page ${i} of ${pageCount}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
      doc.setTextColor(0, 0, 0);
    }
  };

  // Header Section
  doc.setFillColor(41, 55, 72); // primary color
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(organizationName, margin, 20);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(projectTitle, margin, 32);
  
  doc.setTextColor(0, 0, 0);
  yPosition = 55;

  // Contact Information
  addText('Contact Information', 12, true);
  yPosition += 5;
  addText(`${contactInfo.name}, ${contactInfo.title}`);
  addText(`Email: ${contactInfo.email} | Phone: ${contactInfo.phone}`);
  yPosition += 10;

  // Full Grant Proposal Section
  doc.setFillColor(59, 130, 246); // accent color
  doc.rect(margin, yPosition, maxWidth, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Full Grant Proposal', margin + 5, yPosition + 6);
  doc.setTextColor(0, 0, 0);
  yPosition += 15;

  addText(proposal);
  yPosition += 15;

  // Letter of Intent Section
  if (loi) {
    if (yPosition > pageHeight - 80) {
      doc.addPage();
      yPosition = margin;
    }

    doc.setFillColor(16, 185, 129); // secondary color
    doc.rect(margin, yPosition, maxWidth, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Letter of Intent', margin + 5, yPosition + 6);
    doc.setTextColor(0, 0, 0);
    yPosition += 15;

    addText(loi);
  }

  // Add footers to all pages
  addFooter();

  return doc;
}
