import jsPDF from 'jspdf';
import 'jspdf-autotable';

interface TimeBlock {
  time: string;
  activity: string;
  category: 'work' | 'personal' | 'side-business' | 'rest';
}

interface DaySchedule {
  [key: string]: TimeBlock[];
}

interface ScheduleSummary {
  totalCommittedHours: number;
  totalAvailableHours: number;
  sideBusinessHours: number;
  personalTime: number;
  recommendations: string[];
}

interface ScheduleData {
  weeklySchedule: DaySchedule;
  summary: ScheduleSummary;
}

export function generateSchedulePDF(scheduleData: ScheduleData, userName: string = 'User'): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;

  // Color mappings
  const categoryColors: Record<string, [number, number, number]> = {
    'work': [59, 130, 246],           // Blue
    'personal': [16, 185, 129],       // Green
    'side-business': [139, 92, 246],  // Purple
    'business': [139, 92, 246],       // Purple (add both variants)
    'rest': [100, 100, 100],          // Medium gray
    'family': [236, 72, 153],         // Pink
    'fitness': [34, 197, 94],         // Bright green
    'faith': [168, 85, 247],          // Light purple
    'health': [239, 68, 68],          // Red
    'study': [251, 146, 60],          // Orange
    'personal-development': [14, 165, 233], // Sky blue
    'creativity': [249, 115, 22],     // Dark orange
    'marriage': [244, 63, 94],        // Rose
    'children': [250, 204, 21]        // Yellow
  };

  // Header
  doc.setFillColor(41, 55, 72);
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(`${userName}'s Personalized Schedule`, margin, 15);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by PivotHub', margin, 25);
  doc.text(new Date().toLocaleDateString(), pageWidth - margin - 30, 25);
  
  doc.setTextColor(0, 0, 0);
  let yPos = 45;

  // Summary Statistics Box
  doc.setFillColor(245, 245, 245);
  doc.rect(margin, yPos, pageWidth - 2 * margin, 35, 'F');
  doc.setDrawColor(200, 200, 200);
  doc.rect(margin, yPos, pageWidth - 2 * margin, 35, 'S');
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Weekly Summary', margin + 5, yPos + 8);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Total Committed Hours: ${scheduleData.summary.totalCommittedHours}`, margin + 5, yPos + 16);
  doc.text(`Side Business Hours: ${scheduleData.summary.sideBusinessHours}`, margin + 5, yPos + 23);
  doc.text(`Personal Time: ${scheduleData.summary.personalTime}`, margin + 5, yPos + 30);
  
  yPos += 45;

  // Weekly Schedule Grid
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Weekly Schedule', margin, yPos);
  yPos += 8;

  const days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
  const dayNames = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

  days.forEach((day, index) => {
    const daySchedule = scheduleData.weeklySchedule[day] || [];
    
    // Increased safety margin: 80 units ensures footer + day header + at least 3 blocks fit
    if (yPos > pageHeight - 80) {
      doc.addPage();
      yPos = margin;
    }

    // Day header
    doc.setFillColor(59, 130, 246);
    doc.rect(margin, yPos, pageWidth - 2 * margin, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(dayNames[index], margin + 3, yPos + 5.5);
    doc.setTextColor(0, 0, 0);
    yPos += 10;

    // Time blocks for this day
    if (daySchedule.length > 0) {
      daySchedule.forEach((block: TimeBlock) => {
        // CHECK: Will this block fit on current page?
        // Each block needs 12 units, footer needs 15 units safety
        if (yPos > pageHeight - 30) {
          doc.addPage();
          yPos = margin;
          
          // Re-add day header on new page
          doc.setFillColor(59, 130, 246);
          doc.rect(margin, yPos, pageWidth - 2 * margin, 8, 'F');
          doc.setTextColor(255, 255, 255);
          doc.setFontSize(11);
          doc.setFont('helvetica', 'bold');
          doc.text(dayNames[index] + ' (continued)', margin + 3, yPos + 5.5);
          doc.setTextColor(0, 0, 0);
          yPos += 10;
        }
        
        const color = categoryColors[block.category] || [220, 220, 220]; // Default to light gray
        
        // Create light pastel background colors (add 100 to each RGB channel)
        const lightColor: [number, number, number] = [
          Math.min(255, color[0] + 100),
          Math.min(255, color[1] + 100),
          Math.min(255, color[2] + 100)
        ];
        
        // Use light pastel background
        doc.setFillColor(lightColor[0], lightColor[1], lightColor[2]);
        doc.rect(margin, yPos, pageWidth - 2 * margin, 10, 'F');
        
        // Use subtle border with original color at low opacity
        doc.setDrawColor(color[0], color[1], color[2]);
        doc.setLineWidth(0.3);
        doc.rect(margin, yPos, pageWidth - 2 * margin, 10, 'S');
        
        // Use BLACK text for maximum readability
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text(block.time, margin + 3, yPos + 4);
        doc.setFont('helvetica', 'normal');
        doc.text(block.activity, margin + 3, yPos + 8);
        
        yPos += 12;
      });
    } else {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(128, 128, 128);
      doc.text('No scheduled activities', margin + 3, yPos + 4);
      doc.setTextColor(0, 0, 0);
      yPos += 10;
    }
    
    yPos += 5;
  });

  // Recommendations
  if (scheduleData.summary.recommendations.length > 0) {
    // Ensure at least 90 units for recommendations header + multiple lines + footer
    if (yPos > pageHeight - 90) {
      doc.addPage();
      yPos = margin;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Recommendations', margin, yPos);
    yPos += 8;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    scheduleData.summary.recommendations.forEach((rec: string) => {
      const lines = doc.splitTextToSize(`• ${rec}`, pageWidth - 2 * margin - 5);
      lines.forEach((line: string) => {
        // Ensure at least 30 units for line + footer safety
        if (yPos > pageHeight - 30) {
          doc.addPage();
          yPos = margin;
        }
        doc.text(line, margin + 3, yPos);
        yPos += 5;
      });
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128, 128, 128);
    doc.text(
      'This schedule is not stored in PivotHub. Please save this PDF for your records.',
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
    doc.setTextColor(0, 0, 0);
  }

  return doc;
}
