import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { FileText } from 'lucide-react';

const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      {/* Hero Section */}
      <section className="py-20 bg-gradient-hero">
        <div className="container mx-auto px-4">
          <div className="text-center max-w-4xl mx-auto">
            <div className="w-16 h-16 bg-white/10 rounded-2xl flex items-center justify-center mx-auto mb-6">
              <FileText className="h-8 w-8 text-white" />
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-white leading-tight">
              Terms and Conditions
            </h1>
            <p className="text-lg md:text-xl text-white/90 font-light leading-relaxed">
              Please read these terms and conditions carefully before using PivotHub services
            </p>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto">
          <Card>
            <CardHeader>
              <CardTitle>Terms of Service</CardTitle>
            </CardHeader>
            <CardContent className="space-y-8 prose prose-gray max-w-none">
              <div>
                <p className="text-muted-foreground leading-relaxed">
                  Welcome to the website operated by PivotHub ("Company," "we," "our," or "us"). By accessing or using this website and its tools, you agree to be bound by the following Terms and Conditions. If you do not agree with these terms, please do not use this site.
                </p>
              </div>

              <div>
                <h3 className="text-xl font-semibold mb-4">1. Disclaimer of Liability</h3>
                <p className="text-muted-foreground leading-relaxed">
                  PivotHub provides access to artificial intelligence (AI)-powered tools and platforms for informational, educational, and professional development purposes. We act solely as an intermediary, connecting users with generative AI technologies.
                </p>
                <p className="text-muted-foreground leading-relaxed">
                  We do not guarantee the accuracy, legality, completeness, or usefulness of any AI-generated content, and we make no warranties, expressed or implied, as to the outcomes or decisions based on such content.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-2">
                  By using this website, you acknowledge and agree that:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                  <li>You are solely responsible for how you use the tools and any resulting content.</li>
                  <li>PivotHub shall not be held liable for any decisions, losses, damages, or legal outcomes (including but not limited to employment, financial, reputational, or emotional consequences) resulting from the use of this platform.</li>
                  <li>You use the AI tools and their outputs entirely at your own risk.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-xl font-semibold mb-4">2. Copyright and Intellectual Property</h3>
                <p className="text-muted-foreground leading-relaxed">
                  AI-generated content, including but not limited to text and images, may not be original and could unintentionally resemble or replicate existing copyrighted materials.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-2">
                  By using this site, you understand and agree that:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                  <li>PivotHub assumes no responsibility or liability for any potential copyright, intellectual property, or legal disputes that may arise from AI-generated content.</li>
                  <li>You are solely responsible for ensuring that any content you publish or distribute complies with applicable copyright and intellectual property laws.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-xl font-semibold mb-4">3. No Professional Advice</h3>
                <p className="text-muted-foreground leading-relaxed">
                  The outputs of any AI tools available on this site do not constitute professional, legal, business, or career advice. Users should consult with appropriate professionals before making decisions based on the information generated by this platform.
                </p>
              </div>

              <div>
                <h3 className="text-xl font-semibold mb-4">4. Consent and Use</h3>
                <p className="text-muted-foreground leading-relaxed mb-2">
                  By accessing or using this website, you confirm that you:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                  <li>Are at least 18 years old or have the permission of a parent or legal guardian.</li>
                  <li>Agree to these Terms and Conditions and any future updates.</li>
                  <li>Assume full responsibility for how you use any content or tools on this platform.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-xl font-semibold mb-4">5. Jurisdiction</h3>
                <p className="text-muted-foreground leading-relaxed">
                  These terms shall be governed by and construed in accordance with the laws of the State of Michigan, without regard to conflict of law principles. Any legal action or proceeding arising from your use of the website shall be brought exclusively in a court located in Michigan.
                </p>
              </div>

              <div>
                <h3 className="text-xl font-semibold mb-4">6. Changes to Terms</h3>
                <p className="text-muted-foreground leading-relaxed">
                  We reserve the right to modify these Terms and Conditions at any time. Continued use of the website after any such changes shall constitute your consent to the updated terms.
                </p>
              </div>

              <div className="pt-4 border-t">
                <p className="text-sm text-muted-foreground">
                  Last updated: {new Date().toLocaleDateString()}
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default TermsAndConditions;