// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://app.pivothub.io";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrdmpzZ3FqZ2lzc29scGRxYmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzQxMTAsImV4cCI6MjA3MDAxMDExMH0.v6_C4ocJdS_9BtegfsYc3N1TbBzvGJDFDdGpuepTxyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});